let rel = function getDrops(codCe, anoLetivo, platInquerit, nrIscrit, nrIscritUC, nrRespost1Sem, perResp1Sem, nrRespost2Sem, perResp2Sem, clarezaUC, grauInteresse, articOutUC, grauDificul, relConteudo, articulAulas, dispBiblio, claroElemAval, DispMeios, ArticulRealid, media, NrIncriUltAno,NrDiplom ,TxAprov ,graduados3anos, graduados2anos, graduados1ano, graduadosNAnos3anos, graduadosNAnos2anos, graduadosNAnos1anos, graduadosN1Anos3anos, graduadosN1Anos2anos, graduadosN1Anos1anos, graduadosN2Anos3anos, graduadosN2Anos2anos, graduadosN2Anos1anos, graduadosN2MAnos3anos, graduadosN2MAnos2anos, graduadosN2MAnos1anos, ativComunidade, ativInvestig, pontosFortes, acoesFormac, sugestMelhoria, considFinais, dtaSophUC, dtaSophInscri, dtaSophDiplom, dtaSophInter, estudEstragAnt, estudEstragPen, estudEstragUlt, estudMobInAnt, estudMobInPen, estudMobInUlt, estudMobOutAnt, estudMobOutPen, estudMobOutUlt, estudDocInAnt, estudDocInPen, estudDocInUlt, estudDocOutAnt, estudDocOutPen, estudDocOutUlt, estudStaffInAnt, estudStaffInPen, estudStaffInUlt, estudStaffOutAnt, estudStaffOutPen, estudStaffOutUlt, tbIntRev, wosq1, wosq2, wosq3, wosq4, wosn, elsq1, elsq2, elsq3, elsq4, elsn, sjrq1, sjrq2, sjrq3, sjrq4, sjrn, outn, pubTot, lbRevCient, lbLivro, lbAtas, lbOutPub, callback){
	var sql = require('./db.js');
	
	sql.query("call Qualidade.setRelCE(" + codCe + ",'" + anoLetivo + "','" + platInquerit + "'," + nrIscrit + "," + nrIscritUC + "," + nrRespost1Sem + ","+ perResp1Sem + "," + nrRespost2Sem + "," + perResp2Sem + "," + clarezaUC + "," +  grauInteresse + "," + articOutUC + "," + grauDificul + "," + relConteudo + "," +  articulAulas + "," + dispBiblio + "," + claroElemAval + "," + DispMeios + "," + ArticulRealid + "," + media + "," + NrIncriUltAno + "," + NrDiplom + "," + TxAprov + "," +  graduados3anos +"," + graduados2anos + "," +  graduados1ano + "," +  graduadosNAnos3anos + "," + graduadosNAnos2anos + "," + graduadosNAnos1anos + "," +  graduadosN1Anos3anos + "," + graduadosN1Anos2anos + "," + graduadosN1Anos1anos + "," + graduadosN2Anos3anos + "," + graduadosN2Anos2anos + "," +  graduadosN2Anos1anos + "," + graduadosN2MAnos3anos + "," + graduadosN2MAnos2anos + "," + graduadosN2MAnos1anos + ", '" + ativComunidade + "','" +  ativInvestig + "','" + pontosFortes + "','" +  acoesFormac + "', '" + sugestMelhoria + "', '" +  considFinais + "','" + dtaSophUC + "','" + dtaSophInscri + "','" + dtaSophDiplom + "','" + dtaSophInter + "'," + estudEstragAnt + "," + estudEstragPen + "," + estudEstragUlt + "," + estudMobInAnt + "," + estudMobInPen + "," + estudMobInUlt + "," + estudMobOutAnt + "," + estudMobOutPen + "," + estudMobOutUlt + "," + estudDocInAnt + "," + estudDocInPen + "," + estudDocInUlt + "," + estudDocOutAnt + "," + estudDocOutPen + "," + estudDocOutUlt + "," + estudStaffInAnt + "," + estudStaffInPen + "," + estudStaffInUlt + "," + estudStaffOutAnt + "," + estudStaffOutPen + "," + estudStaffOutUlt + ",'" + tbIntRev + "'," + wosq1 + "," + wosq2 + "," + wosq3 + "," + wosq4 + "," + wosn + "," + elsq1 + "," + elsq2 + "," + elsq3 + "," + elsq4 + "," + elsn + "," + sjrq1 + "," + sjrq2 + "," + sjrq3 + "," + sjrq4 + "," + sjrn + "," + outn + "," + pubTot + ",'" + lbRevCient + "','" + lbLivro + "','" + lbAtas + "','" + lbOutPub + "', 0)", (err, result) => {
		if(err){
			console.log(err);
		}else{
			callback(null, result);
		}
	})
}

module.exports = rel;